apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gatest-api
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gatest-api
    spec:
      containers:
        - name: gatest-api
          image: registry-intl.ap-southeast-5.aliyuncs.com/musteat/gatest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: gatest-api-port
