apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
      containers:
        - name: api
          image: registry-intl.ap-southeast-5.aliyuncs.com/musteat/gatest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: api-port
