apiVersion: v1
kind: Service
metadata:
  name: gatest-api
  annotations:
  labels:
    app: gatest-api
  namespace: development
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 3000
      protocol: TCP
      name: api-port
  selector:
    app: gatest-api
