name: Main Workflow

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [11.14.0]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: npm test
      run: |
        npm test
      env:
        CI: true
  update_draft_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_publish_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create and Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gatest:1.0.0
          username: ${{ secrets.ALIBABA_DOCKER_USERNAME }}
          password: ${{ secrets.ALIBABA_DOCKER_PASSWORD }}
          registry: ${{ secrets.ALIBABA_REGISTRY_URL }}
          dockerfile: Dockerfile
