name: Master Deployment Workflow

on:
  release:
    types: [published]
jobs:
  job_1:
    name: Build, Push, Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
      - name: Get the version of release
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build and Push image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gatest:${{steps.get_version.outputs.VERSION}}
          username: ${{ secrets.ALIBABA_DOCKER_USERNAME }}
          password: ${{ secrets.ALIBABA_DOCKER_PASSWORD }}
          registry: ${{ secrets.ALIBABA_REGISTRY_URL }}
          dockerfile: Dockerfile
          snapshot: true
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.16.1' # default is latest stable
        id: install
      - name: Config the KUBECONFIG
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: ${{ secrets.ALIBABA_KUBE_CONFIG }}
      - name: Set kubectl context
        run: |
          kubectl config use-context ME-Integration
          kubectl config view
          kubectl config current-context
      - name: Deployment image to server
        uses: azure/k8s-actions/k8s-deploy@master
        with:
          namespace: development
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            ${{ secrets.ALIBABA_REGISTRY_URL }}/gatest:${{steps.get_version.outputs.VERSION}}
          imagepullsecrets: |
            regcred
