name: Create and publish Workflow

on:
  release:
    types: [published]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create and Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gatest:${{steps.get_version.outputs.VERSION}}
          username: ${{ secrets.ALIBABA_DOCKER_USERNAME }}
          password: ${{ secrets.ALIBABA_DOCKER_PASSWORD }}
          registry: ${{ secrets.ALIBABA_REGISTRY_URL }}
          dockerfile: Dockerfile
          snapshot: true
  deploy:
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - name: setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.16.1' # default is latest stable
        id: install
      - name: set context
        uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: ${{ secrets.ALIBABA_KUBE_CONFIG }}
        run: |
          kubectl config view
          kubectl config current-context
