name: Create and publish Workflow

on:
  release:
    types: [published]
jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Build container image
        uses: actions/docker/cli@master
        with:
          args: build -t ${{ secrets.ALIBABA_REGISTRY_URL }}/gatest:$(echo $GITHUB_SHA | head -c7) .

      - name: Docker Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.ALIBABA_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ALIBABA_DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        uses: actions/docker/cli@master
        with:
          args: push ${{ secrets.ALIBABA_REGISTRY_URL }}/gatest:$(echo $GITHUB_SHA | head -c7)
