name: Create and publish Workflow

on:
  release:
    types: [published]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create and Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: gatest:${{steps.get_version.outputs.VERSION}}
          username: ${{ secrets.ALIBABA_DOCKER_USERNAME }}
          password: ${{ secrets.ALIBABA_DOCKER_PASSWORD }}
          registry: ${{ secrets.ALIBABA_REGISTRY_URL }}
          dockerfile: Dockerfile
          snapshot: true
  deploy:
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - name: check kubectl version
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: version
      - name: use context me-integration
          uses: steebchen/kubectl@master
          env:
            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          with:
            args: config use-context ME-Integration
